running tests with an empty config

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -1,12 +1,14 @@
 #!/bin/bash
 
+echo "" > config
+
 FAILURES=
 echo "Running tests"
 for foo in *.io
 do
 	echo " - $foo"
-	cat "$foo" | "$@" > /dev/null 2>&1
-	cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "RESULT:"; cat -A $foo.ok; echo "WANTED:"; cat -A $foo.out;FAILURES="$foo $FAILURES"; }
+	cat "$foo" | "$@" -c config > /dev/null 2>&1
+	cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "WANTED:"; cat -A $foo.ok; echo "RESULT:"; cat -A $foo.out;FAILURES="$foo $FAILURES"; }
 	rm "$foo.out"
 done
 
