overdue merge from development pi. parallel tests, abbreviations, etc.

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -1,19 +1,21 @@
 #!/bin/bash
 
 echo "" > config
+test -f failures && rm failures
 
-FAILURES=
-echo "Running tests"
+echo "Startins tests"
 for foo in *.io
 do
    echo " - $foo"
-   cat "$foo" | "$@" -c config > /dev/null 2>&1
-   cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "WANTED:"; cat -A $foo.ok; echo "RESULT:"; cat -A $foo.out;FAILURES="$foo $FAILURES"; }
-   rm "$foo.out"
+   (cat "$foo" | "$@" -c config > /dev/null 2>&1;
+    cmp "$foo.out" "$foo.ok" || { echo "Test $foo failed: $(diff $foo.ok $foo.out)"; echo "WANTED:"; cat -A $foo.ok; echo "RESULT:"; cat -A $foo.out;echo "$foo" >> failures; };
+    rm "$foo.out") &
 done
 
-rm config
+echo "Running tests"
+wait
 
-test -n "$FAILURES" && echo "Failed tests: $FAILURES" && exit 1
+test -s failures && echo "Tests failed: $(cat failures)" && exit 1
 
-echo "Tests OK"
+rm failures config 2>/dev/null
+echo "Tests passed"
